dvariables(['Libros'=Libros,'CantPrestada'=CantPrestada,'Prestamos'=Prestamos]).
dinvariant(invTipo,invTipo(Libros,CantPrestada,Prestamos)).
dinvariant(bibliotecaInv,bibliotecaInv(CantPrestada,Libros)).
dinitial(bibliotecaInit(Libros,CantPrestada,Prestamos)).
all_unsat_vc(altaLibro_pi_invTipo,inv,invTipo,altaLibro_pi_invTipo(Libros,CantPrestada,Prestamos,Libros,CantPrestada,Prestamos,L,N,Libros_,CantPrestada_,Prestamos_),altaLibro(Libros,CantPrestada,Prestamos,L,N,Libros_,CantPrestada_,Prestamos_)).
all_unsat_vc(altaLibro_pi_bibliotecaInv,inv,bibliotecaInv,altaLibro_pi_bibliotecaInv(CantPrestada,Libros,Libros,CantPrestada,Prestamos,L,N,Libros_,CantPrestada_,Prestamos_),altaLibro(Libros,CantPrestada,Prestamos,L,N,Libros_,CantPrestada_,Prestamos_)).
all_unsat_vc(consultarLibro_pi_invTipo,inv,invTipo,consultarLibro_pi_invTipo(Libros,CantPrestada,Prestamos,Libros,CantPrestada,Prestamos,L,N,M),consultarLibro(Libros,CantPrestada,Prestamos,L,N,M)).
all_unsat_vc(consultarLibro_pi_bibliotecaInv,inv,bibliotecaInv,consultarLibro_pi_bibliotecaInv(CantPrestada,Libros,Libros,CantPrestada,Prestamos,L,N,M),consultarLibro(Libros,CantPrestada,Prestamos,L,N,M)).
all_unsat_vc(prestarLibro_pi_invTipo,inv,invTipo,prestarLibro_pi_invTipo(Libros,CantPrestada,Prestamos,Libros,CantPrestada,Prestamos,L,S,M,Libros_,CantPrestada_,Prestamos_),prestarLibro(Libros,CantPrestada,Prestamos,L,S,M,Libros_,CantPrestada_,Prestamos_)).
all_unsat_vc(prestarLibro_pi_bibliotecaInv,inv,bibliotecaInv,prestarLibro_pi_bibliotecaInv(CantPrestada,Libros,Libros,CantPrestada,Prestamos,L,S,M,Libros_,CantPrestada_,Prestamos_),prestarLibro(Libros,CantPrestada,Prestamos,L,S,M,Libros_,CantPrestada_,Prestamos_)).
